local Players = game:GetService("Players")
local RunService = game:GetService("RunService")
local UserInputService = game:GetService("UserInputService")
local CoreGui = game:GetService("CoreGui")

local player = Players.LocalPlayer
local camera = workspace.CurrentCamera

-- =============================================================================
-- INTERFACE GRAPHIQUE (UI STYLE SOMBRE & VERT)
-- =============================================================================

local ScreenGui = Instance.new("ScreenGui")
ScreenGui.Name = "ExpertDeveloperMenu"
ScreenGui.ResetOnSpawn = false
ScreenGui.Parent = CoreGui -- Utiliser player:WaitForChild("PlayerGui") si testé hors Studio

-- Fenêtre Principale
local MainFrame = Instance.new("Frame")
MainFrame.Size = UDim2.new(0, 500, 0, 320)
MainFrame.Position = UDim2.new(0.5, -250, 0.5, -160)
MainFrame.BackgroundColor3 = Color3.fromRGB(15, 15, 15)
MainFrame.Active = true
MainFrame.Draggable = true
MainFrame.Parent = ScreenGui

local MainCorner = Instance.new("UICorner")
MainCorner.CornerRadius = UDim.new(0, 8)
MainCorner.Parent = MainFrame

local MainStroke = Instance.new("UIStroke")
MainStroke.Color = Color3.fromRGB(0, 255, 100)
MainStroke.Thickness = 1.5
MainStroke.Parent = MainFrame

-- Barre Latérale (Menu de Gauche)
local Sidebar = Instance.new("Frame")
Sidebar.Size = UDim2.new(0, 140, 1, 0)
Sidebar.BackgroundColor3 = Color3.fromRGB(22, 22, 22)
Sidebar.Parent = MainFrame

local SideCorner = Instance.new("UICorner")
SideCorner.CornerRadius = UDim.new(0, 8)
SideCorner.Parent = Sidebar

-- Titre
local Title = Instance.new("TextLabel")
Title.Size = UDim2.new(1, 0, 0, 40)
Title.BackgroundTransparency = 1
Title.Text = "DEVELOPER HUB"
Title.TextColor3 = Color3.fromRGB(0, 255, 100)
Title.Font = Enum.Font.GothamBold
Title.TextSize = 14
Title.Parent = Sidebar

-- Zones de Contenu (Pages de Droite)
local Container = Instance.new("Frame")
Container.Size = UDim2.new(1, -150, 1, -20)
Container.Position = UDim2.new(0, 145, 0, 10)
Container.BackgroundTransparency = 1
Container.Parent = MainFrame

local PageAccueil = Instance.new("Frame")
PageAccueil.Size = UDim2.new(1, 0, 1, 0)
PageAccueil.BackgroundTransparency = 1
PageAccueil.Visible = true
PageAccueil.Parent = Container

local WelcomeText = Instance.new("TextLabel")
WelcomeText.Size = UDim2.new(1, 0, 0, 50)
WelcomeText.BackgroundTransparency = 1
WelcomeText.Text = "Bienvenue dans votre outil de test"
WelcomeText.TextColor3 = Color3.fromRGB(255, 255, 255)
WelcomeText.Font = Enum.Font.GothamSemibold
WelcomeText.TextSize = 16
WelcomeText.Parent = PageAccueil

local PageMultigame = Instance.new("Frame")
PageMultigame.Size = UDim2.new(1, 0, 1, 0)
PageMultigame.BackgroundTransparency = 1
PageMultigame.Visible = false
PageMultigame.Parent = Container

-- =============================================================================
-- LOGIQUE DU FLY & VARIABLES DE CONTROLE
-- =============================================================================

local flying = false
local flySpeed = 50
local currentWalkspeed = 16

local bodyGyro, bodyVelocity
local keysDown = {}

local function startFly()
	local character = player.Character
    	if not character or not character:FindFirstChild("HumanoidRootPart") then return end
        	local root = character.HumanoidRootPart
            	local humanoid = character:FindFirstChildOfClass("Humanoid")
                	if humanoid then humanoid.PlatformStand = true end

                    	bodyGyro = Instance.new("BodyGyro")
                        	bodyGyro.P = 9e4
                            	bodyGyro.maxTorque = Vector3.new(9e9, 9e9, 9e9)
                                	bodyGyro.cframe = root.CFrame
                                    	bodyGyro.Parent = root

                                        	bodyVelocity = Instance.new("BodyVelocity")
                                            	bodyVelocity.velocity = Vector3.new(0, 0.1, 0)
                                                	bodyVelocity.maxForce = Vector3.new(9e9, 9e9, 9e9)
                                                    	bodyVelocity.Parent = root

                                                        	flying = true

                                                            	task.spawn(function()
                                                                		while flying and root and bodyVelocity and bodyGyro do
                                                                        			RunService.RenderStepped:Wait()
                                                                                    			local camCFrame = camera.CFrame
                                                                                                			local direction = Vector3.new(0, 0, 0)
                                                                                                            
                                                                                                            			-- Déplacements WASD / ZQSD (Prend en compte la configuration clavier)
                                                                                                                        			if keysDown[Enum.KeyCode.W] or keysDown[Enum.KeyCode.Z] then
                                                                                                                                    				direction = direction + camCFrame.LookVector
                                                                                                                                                    			end
                                                                                                                                                                			if keysDown[Enum.KeyCode.S] then
                                                                                                                                                                            				direction = direction - camCFrame.LookVector
                                                                                                                                                                                            			end
                                                                                                                                                                                                        			if keysDown[Enum.KeyCode.A] or keysDown[Enum.KeyCode.Q] then
                                                                                                                                                                                                                    				direction = direction - camCFrame.RightVector
                                                                                                                                                                                                                                    			end
                                                                                                                                                                                                                                                			if keysDown[Enum.KeyCode.D] then
                                                                                                                                                                                                                                                            				direction = direction + camCFrame.RightVector
                                                                                                                                                                                                                                                                            			end
                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                        			-- Élévation (Espace / Ctrl)
                                                                                                                                                                                                                                                                                                    			if keysDown[Enum.KeyCode.Space] then
                                                                                                                                                                                                                                                                                                                				direction = direction + Vector3.new(0, 1, 0)
                                                                                                                                                                                                                                                                                                                                			end
                                                                                                                                                                                                                                                                                                                                            			if keysDown[Enum.KeyCode.LeftControl] then
                                                                                                                                                                                                                                                                                                                                                        				direction = direction - Vector3.new(0, 1, 0)
                                                                                                                                                                                                                                                                                                                                                                        			end
                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                    			bodyGyro.cframe = camCFrame
                                                                                                                                                                                                                                                                                                                                                                                                			if direction.Magnitude > 0 then
                                                                                                                                                                                                                                                                                                                                                                                                            				bodyVelocity.velocity = direction.Unit * flySpeed
                                                                                                                                                                                                                                                                                                                                                                                                                            			else
                                                                                                                                                                                                                                                                                                                                                                                                                                        				bodyVelocity.velocity = Vector3.new(0, 0, 0)
                                                                                                                                                                                                                                                                                                                                                                                                                                                        			end
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    		end
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            	end)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                end

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                local function stopFly()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                	flying = false
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    	if bodyGyro then bodyGyro:Destroy() end
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        	if bodyVelocity then bodyVelocity:Destroy() end
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            	local character = player.Character
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                	if character then
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    		local humanoid = character:FindFirstChildOfClass("Humanoid")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            		if humanoid then humanoid.PlatformStand = false end
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    	end
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        end

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        UserInputService.InputBegan:Connect(function(input, gameProcessed)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        	if gameProcessed then return end
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            	keysDown[input.KeyCode] = true
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                end)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                UserInputService.InputEnded:Connect(function(input)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                	keysDown[input.KeyCode] = nil
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    end)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    -- =============================================================================
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    -- ÉLÉMENTS DE LA PAGE MULTIGAME (BOUTONS & COMMANDES)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    -- =============================================================================

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    -- Bouton d'activation du Fly
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    local FlyBtn = Instance.new("TextButton")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    FlyBtn.Size = UDim2.new(0, 200, 0, 40)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    FlyBtn.Position = UDim2.new(0, 10, 0, 20)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    FlyBtn.BackgroundColor3 = Color3.fromRGB(30, 30, 30)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    FlyBtn.Text = "Activer Fly : OFF"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    FlyBtn.TextColor3 = Color3.fromRGB(255, 100, 100)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    FlyBtn.Font = Enum.Font.Gotham
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    FlyBtn.TextSize = 14
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    FlyBtn.Parent = PageMultigame

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    local FlyCorner = Instance.new("UICorner")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    FlyCorner.CornerRadius = UDim.new(0, 6)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    FlyCorner.Parent = FlyBtn

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    FlyBtn.MouseButton1Click:Connect(function()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    	if not flying then
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        		startFly()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                		FlyBtn.Text = "Activer Fly : ON"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        		FlyBtn.TextColor3 = Color3.fromRGB(100, 255, 100)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                	else
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    		stopFly()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            		FlyBtn.Text = "Activer Fly : OFF"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    		FlyBtn.TextColor3 = Color3.fromRGB(255, 100, 100)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            	end
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                end)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                -- Gestion de la Vitesse (WalkSpeed)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                local SpeedLabel = Instance.new("TextLabel")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                SpeedLabel.Size = UDim2.new(0, 200, 0, 30)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                SpeedLabel.Position = UDim2.new(0, 10, 0, 80)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                SpeedLabel.BackgroundTransparency = 1
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                SpeedLabel.Text = "Vitesse : " .. currentWalkspeed
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                SpeedLabel.TextColor3 = Color3.fromRGB(255, 255, 255)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                SpeedLabel.Font = Enum.Font.Gotham
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                SpeedLabel.TextSize = 14
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                SpeedLabel.TextXAlignment = Enum.TextXAlignment.Left
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                SpeedLabel.Parent = PageMultigame

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                local function updateSpeed(value)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                	currentWalkspeed = math.clamp(currentWalkspeed + value, 0, 250)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    	SpeedLabel.Text = "Vitesse : " .. currentWalkspeed
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        	local character = player.Character
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            	if character then
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                		local humanoid = character:FindFirstChildOfClass("Humanoid")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        		if humanoid then humanoid.WalkSpeed = currentWalkspeed end
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                	end
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    end

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    local BtnPlus = Instance.new("TextButton")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    BtnPlus.Size = UDim2.new(0, 40, 0, 30)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    BtnPlus.Position = UDim2.new(0, 10, 0, 120)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    BtnPlus.BackgroundColor3 = Color3.fromRGB(30, 30, 30)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    BtnPlus.Text = "+"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    BtnPlus.TextColor3 = Color3.fromRGB(255, 255, 255)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    BtnPlus.Font = Enum.Font.GothamBold
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    BtnPlus.TextSize = 16
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    BtnPlus.Parent = PageMultigame
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    Instance.new("UICorner", BtnPlus).CornerRadius = UDim.new(0, 4)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    BtnPlus.MouseButton1Click:Connect(function()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    	updateSpeed(10)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        end)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        local BtnMoins = Instance.new("TextButton")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        BtnMoins.Size = UDim2.new(0, 40, 0, 30)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        BtnMoins.Position = UDim2.new(0, 60, 0, 120)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        BtnMoins.BackgroundColor3 = Color3.fromRGB(30, 30, 30)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        BtnMoins.Text = "-"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        BtnMoins.TextColor3 = Color3.fromRGB(255, 255, 255)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        BtnMoins.Font = Enum.Font.GothamBold
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        BtnMoins.TextSize = 16
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        BtnMoins.Parent = PageMultigame
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Instance.new("UICorner", BtnMoins).CornerRadius = UDim.new(0, 4)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        BtnMoins.MouseButton1Click:Connect(function()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        	updateSpeed(-10)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            end)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            -- Mettre à jour la vitesse si le personnage réapparaît
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            player.CharacterAdded:Connect(function(char)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            	local humanoid = char:WaitForChild("Humanoid")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                	humanoid.WalkSpeed = currentWalkspeed
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    	if flying then stopFly() FlyBtn.Text = "Activer Fly : OFF" FlyBtn.TextColor3 = Color3.fromRGB(255, 100, 100) end
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        end)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        -- =============================================================================
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        -- SYSTEME D'ONGLETS DE NAVIGATION
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        -- =============================================================================

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        local TabAccueil = Instance.new("TextButton")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        TabAccueil.Size = UDim2.new(1, -20, 0, 35)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        TabAccueil.Position = UDim2.new(0, 10, 0, 50)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        TabAccueil.BackgroundColor3 = Color3.fromRGB(35, 35, 35)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        TabAccueil.Text = "Accueil"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        TabAccueil.TextColor3 = Color3.fromRGB(255, 255, 255)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        TabAccueil.Font = Enum.Font.GothamSemibold
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        TabAccueil.TextSize = 12
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        TabAccueil.Parent = Sidebar
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Instance.new("UICorner", TabAccueil).CornerRadius = UDim.new(0, 4)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        local TabMultigame = Instance.new("TextButton")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        TabMultigame.Size = UDim2.new(1, -20, 0, 35)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        TabMultigame.Position = UDim2.new(0, 10, 0, 95)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        TabMultigame.BackgroundColor3 = Color3.fromRGB(25, 25, 25)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        TabMultigame.Text = "Multigame"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        TabMultigame.TextColor3 = Color3.fromRGB(180, 180, 180)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        TabMultigame.Font = Enum.Font.GothamSemibold
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        TabMultigame.TextSize = 12
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        TabMultigame.Parent = Sidebar
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Instance.new("UICorner", TabMultigame).CornerRadius = UDim.new(0, 4)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        TabAccueil.MouseButton1Click:Connect(function()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        	PageAccueil.Visible = true
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            	PageMultigame.Visible = false
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                	TabAccueil.BackgroundColor3 = Color3.fromRGB(35, 35, 35)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    	TabAccueil.TextColor3 = Color3.fromRGB(255, 255, 255)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        	TabMultigame.BackgroundColor3 = Color3.fromRGB(25, 25, 25)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            	TabMultigame.TextColor3 = Color3.fromRGB(180, 180, 180)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                end)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                TabMultigame.MouseButton1Click:Connect(function()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                	PageAccueil.Visible = false
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    	PageMultigame.Visible = true
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        	TabMultigame.BackgroundColor3 = Color3.fromRGB(35, 35, 35)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            	TabMultigame.TextColor3 = Color3.fromRGB(255, 255, 255)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                	TabAccueil.BackgroundColor3 = Color3.fromRGB(25, 25, 25)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    	TabAccueil.TextColor3 = Color3.fromRGB(180, 180, 180)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        end)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        